version: "3.1"
services:


  khz-node:
    build:
      context: ./docker/node
    working_dir: /node
    volumes:
      - ./nodesrc:/node
    ports:
      - "3000:3000"
    networks:
      - krankenhaus-vermittlung
#    command: "npm install -g"
    command: "nodemon --env-file=.env server.js"

  khz-nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d/default.conf
    networks:
      - krankenhaus-vermittlung
    depends_on:
      - khz-node

networks:
  krankenhaus-vermittlung:
    external: true
