version: "3.1"
services:


#  node:
#    image: node
#    container_name: krankenhaus-nodejs
#    ports:
#      - "3000:3000"
#    expose:
#      - "8081"
#    working_dir: /nodesrc
#    volumes:
#      - ./:/nodesrc
#    command: "npm start"

  node:
    image: "node:23"
    user: "node"
    working_dir: /nodesrc
    #working_dir: /home/stefan/Documents/andre_krankenhaus-dummy/nodesrc/package.json
    environment:
      - NODE_ENV=production
    volumes:
      - ./nodesrc:/nodesrc
    expose:
      - "3000"
    ports: # use if it is necessary to expose the container to the host machine
      - "3000:3000"
    command: "node server.js"