FROM node:23


#command: "npm install;node server.js"
WORKDIR /node
#COPY package*.json ./
#RUN pwd
#RUN cd /home/node/app \
#    && npm install
#RUN npm install
#RUN touch test123.txt
RUN npm install nodemon -g

